name: update-predictions

on:
  schedule:
    - cron: "*/15 * * * *"
  workflow_dispatch:
  push:
    branches: [main]

permissions:
  contents: read

concurrency:
  group: deploy-sportacle
  cancel-in-progress: false

jobs:
  refresh:
    runs-on: ubuntu-latest
    steps:
      - run: echo "compile check"
